Adaptions for iOS app
tkem/openlap pull request #81
Opened 2017-09-25 20:39 UTC by elliot2extreme

- Generated icons and splash screens for iOS. Size of icon and splash master image were too small for the generation, therefor I scaled them up (dirty)
- Adaptions in src/app/app.component.ts to fix speech rate on iOS
- Adaptions in src/carrera/data-view.ts to get the app starting in iOS

2017-09-25 21:41 UTC, tkem commented
I think this is a bit much for a single PR, and would be a pain to merge; as it is, it also breaks the build messing with `package.json` etc., which should be outside its scope.
Could you provide a PR with *just* the code changes? This would also be easier to review, without all the images getting in the way ;-)
Regarding images, I guess you mean something like this when running `ionic cordova resources ios`:
```
Error: encountered bad status code (400) for https://res.ionic.io/api/v1/transform
body: {"Error":"source image 2208x2208 too small for Default-Portrait@~ipadpro.png, requires at least 2048x2732 source file"}
```
As you mentioned, just scaling the images is kind of a dirty hack. I'll have a look at the masters and see what I can do next week or so.

2017-09-25 22:00 UTC, tkem commented
You may also want to base you PR on the `develop` branch, which contains updated dependencies and will be the base for the next release (whenever *that* is).

2017-09-26 08:12 UTC, tkem requested changes
PR should only include code changes, preferably as two separate commits since these are unrelated.

2017-09-26 08:12 UTC, tkem commented on src/app/app.component.ts
> +      if (this.platform.is('ios')) {
I think this should be moved to the Speech constructor in `src/core/speech.ts`; also a comment like
```
// See https://github.com/vilic/cordova-plugin-tts/issues/40
```
would make sense for reference.

2017-09-26 08:12 UTC, tkem commented on src/carrera/data-view.ts
> +    let array = new Uint8Array(s.split('').map(c => c.charCodeAt(0)));
Nice catch :+1:

2017-09-26 08:22 UTC, elliot2extreme commented
I will rework my push request to two separate commits based on the develop branch.

2017-09-26 08:45 UTC, tkem commented
:+1:
I will take care of the image issues ASAP; watch https://github.com/tkem/openlap/issues/82

2017-09-27 21:11 UTC, tkem commented
I had some time available, so I simply added your code changes myself to the develop branch (I'll update the changelog/readme and give contribution later, promise). Please check if this works for you now, and feel free to provide more (but maybe a little smaller) PRs if need be.

2017-09-27 21:11 UTC, closed without merging